name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - stage-*



permissions:
  contents: read
  id-token: write



jobs:
  deploy-cf:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.5

      - name: Test
        run: deno task spec

      - name: Build
        run: |-
          deno task pages
          bash ./tools/wwwroot.sh --size 24 --hex ${{ secrets.WWWROOT_SEED }}

      - name: Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ./dist
          name: bip39-recast-${{ github.sha }}
          retention-days: 90

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          wranglerVersion: "4.40.3"
          apiToken:  ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name bip39-recast

